name: Github Pages Build

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4.0.2
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.updateInformationAboutPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
