name: Github Pages Build

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4.0.2
      with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/pages/builds', {
              owner: 'smellems',
              repo: 'devex-pages'
            })

